# ================= SERVER =================
server.port=${PORT}

# ================= MONGODB =================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=hostelDB

# ================= JWT =================
jwt.secret=${JWT_SECRET}

# ================= FILE UPLOAD =================
file.upload-dir=${UPLOAD_DIR}

# ================= LOGGING =================
logging.level.root=INFO
logging.file.name=logs/app.log

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration