# ================= SERVER =================
server.port=8083

# ================= MONGODB =================
spring.data.mongodb.uri=${MONGO_URI}
spring.data.mongodb.database=hostelDB

# ================= JWT =================
jwt.secret=${JWT_SECRET}

# ================= FILE UPLOAD =================
file.upload-dir=${UPLOAD_DIR}

# ================= LOGGING =================
logging.level.root=DEBUG